# github action including pymongo see https://github.com/marketplace/actions/mongodb-in-github-actions

name: TestAndDeploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.8', ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install rdflib
          pip install pytest
          pip install pyyaml

      - name: Run tests
        run: pytest

      # do it manually for the moment...
      #      - name: Prepare widoco
      #          - apt-get update
      #          - apt-get -y install default-jdk zip unzip gawk
      #          - wget https://github.com/dgarijo/Widoco/releases/download/v$WIDOCO_VERSION/widoco-$WIDOCO_VERSION-jar-with-dependencies_JDK-11.jar -O widoco.jar
      #
      #      - name: Run widoco
      #        - dir="temporary-widoco-dir"
      #        - java -jar widoco.jar -ontFile metadata4ing.ttl -outFolder $dir -webVowl -uniteSections -oops -rewriteAll -confFile config.properties
      #        - ls -al $dir
#
#      - name: Deploy
#        run: python deploy.py